# Use NVIDIA's CUDA 12.4 base image
#FROM nvidia/cuda:12.4.0-cudnn8-devel-ubuntu20.04
FROM pytorch/pytorch:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Set the default command
CMD [ "bash" ]

